# Generated by Django 5.2.16 on 2026-07-27 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('specialty_slug', models.CharField(blank=True, default='', max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('workplace', models.CharField(blank=True, default='', max_length=200)),
                ('update_frequency', models.CharField(choices=[('daily', 'Daily'), ('every_3_days', 'Every few days'), ('weekly', 'Weekly')], default='weekly', max_length=15)),
                ('timezone', models.CharField(default='Europe/London', max_length=50)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('feed_last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='catalog.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='UserJournalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('preset', 'From specialty preset'), ('manual', 'Chosen by the user')], default='preset', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='catalog.journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['user'], name='user_journal_active_idx'), models.Index(condition=models.Q(('is_active', True)), fields=['journal'], name='journal_subscribed_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'journal'), name='user_journal_unique')],
            },
        ),
    ]
