# Generated by Django 5.2.16 on 2026-07-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped (lock held)')], default='running', max_length=10)),
                ('command', models.CharField(default='ingest_papers', max_length=60)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('journals_queried', models.IntegerField(default=0)),
                ('articles_fetched', models.IntegerField(default=0)),
                ('papers_created', models.IntegerField(default=0)),
                ('papers_updated', models.IntegerField(default=0)),
                ('specialty_links_created', models.IntegerField(default=0)),
                ('journals_unresolved', models.IntegerField(default=0)),
                ('summaries_attempted', models.IntegerField(default=0)),
                ('summaries_ok', models.IntegerField(default=0)),
                ('summaries_failed', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['-started_at', 'status'], name='ingestion_run_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_found', models.IntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='catalog.journal')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_logs', to='ingestion.ingestionrun')),
            ],
            options={
                'indexes': [models.Index(fields=['journal', '-id'], name='journal_fetch_log_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'journal'), name='journal_fetch_log_unique')],
            },
        ),
    ]
