# Generated by Django 5.2.16 on 2026-07-27 21:06

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=16, unique=True)),
                ('doi', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True, default='')),
                ('journal_name_raw', models.CharField(blank=True, default='', max_length=300)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pub_date_raw', models.CharField(blank=True, default='', max_length=40)),
                ('entrez_date', models.DateField()),
                ('feed_date', models.DateField()),
                ('publication_types', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('mesh_terms', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('category', models.CharField(choices=[('priority', 'Priority'), ('priority_no_abstract', 'Priority (no abstract)'), ('standard', 'Standard'), ('low_priority', 'Low priority'), ('excluded', 'Excluded')], max_length=24)),
                ('is_priority_study', models.BooleanField(default=False)),
                ('is_rct', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True, help_text='Admin kill switch.')),
                ('summary_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('summary_attempts', models.SmallIntegerField(default=0)),
                ('summary_error', models.TextField(blank=True, default='')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, help_text='Null when the journal could not be resolved; see the admin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='catalog.journal')),
            ],
            options={
                'ordering': ('-feed_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaperSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.CharField(choices=[('journal_scope', 'In a specialty journal'), ('topical_match', 'Topically matched')], max_length=20)),
                ('matched_mesh', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('matched_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_links', to='papers.paper')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_links', to='catalog.specialty')),
            ],
            options={
                'verbose_name_plural': 'paper specialties',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='specialties',
            field=models.ManyToManyField(related_name='papers', through='papers.PaperSpecialty', to='catalog.specialty'),
        ),
        migrations.CreateModel(
            name='PaperSummary',
            fields=[
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='papers.paper')),
                ('study_type', models.CharField(max_length=60)),
                ('context', models.TextField()),
                ('finding', models.TextField()),
                ('so_what', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('model_name', models.CharField(max_length=60)),
                ('prompt_version', models.CharField(max_length=40)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'paper summaries',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='summary_tags_gin'), models.Index(fields=['prompt_version'], name='summary_prompt_version_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paperspecialty',
            index=models.Index(fields=['specialty', 'paper'], name='paper_specialty_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='paperspecialty',
            constraint=models.UniqueConstraint(fields=('paper', 'specialty'), name='paper_specialty_unique'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(condition=models.Q(('is_visible', True), ('summary_status', 'ok')), fields=['journal', '-feed_date', '-is_priority_study', '-id'], name='paper_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['-feed_date', '-id'], name='paper_feed_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(condition=models.Q(('summary_status', 'pending')), fields=['summary_status'], name='paper_summary_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['mesh_terms'], name='paper_mesh_gin'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['publication_types'], name='paper_pubtypes_gin'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(condition=models.Q(('doi', ''), _negated=True), fields=('doi',), name='paper_doi_unique'),
        ),
    ]
