# Generated by Django 5.2.16 on 2026-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_paper_doi_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_external',
            field=models.BooleanField(default=False, help_text="Added by a reader's share, not by ingestion."),
        ),
    ]
