# Generated by Django 5.2.16 on 2026-07-27 21:06

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('mesh_terms', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('title_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('abstract_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pubmed_name', models.CharField(max_length=300, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=24)),
                ('nlm_uid', models.CharField(blank=True, default='', max_length=20)),
                ('medline_ta', models.CharField(blank=True, default='', max_length=120)),
                ('issn_print', models.CharField(blank=True, default='', max_length=9)),
                ('issn_electronic', models.CharField(blank=True, default='', max_length=9)),
                ('is_general', models.BooleanField(default=False, help_text='General medical journal — its papers are filtered by specialty relevance.')),
                ('cover_color', models.CharField(default='#1f2937', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Must be a hex colour like #1f2937')])),
                ('cover_color_accent', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Must be a hex colour like #1f2937')])),
                ('cover_style', models.CharField(choices=[('solid', 'Solid'), ('split', 'Split'), ('rule', 'Rule')], default='solid', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name',),
                'indexes': [models.Index(fields=['is_general', 'display_name'], name='catalog_jou_is_gene_c629c9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('nlm_uid', ''), _negated=True), fields=('nlm_uid',), name='journal_nlm_uid_unique'), models.UniqueConstraint(condition=models.Q(('issn_electronic', ''), _negated=True), fields=('issn_electronic',), name='journal_issn_e_unique'), models.UniqueConstraint(condition=models.Q(('issn_print', ''), _negated=True), fields=('issn_print',), name='journal_issn_p_unique')],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True, help_text='Preselected when a user picks this specialty at onboarding.')),
                ('sort_order', models.IntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_links', to='catalog.journal')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_links', to='catalog.specialty')),
            ],
            options={
                'ordering': ('sort_order', 'journal__display_name'),
            },
        ),
        migrations.AddField(
            model_name='specialty',
            name='journals',
            field=models.ManyToManyField(related_name='specialties', through='catalog.SpecialtyJournal', to='catalog.journal'),
        ),
        migrations.CreateModel(
            name='JournalAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pubmed_title', 'PubMed title'), ('medline_ta', 'MEDLINE abbreviation'), ('iso_abbrev', 'ISO abbreviation'), ('issn', 'ISSN'), ('nlm_uid', 'NLM unique ID'), ('manual', 'Manually mapped')], default='manual', max_length=20)),
                ('value', models.CharField(max_length=300)),
                ('value_normalized', models.CharField(editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.journal')),
            ],
            options={
                'verbose_name_plural': 'journal aliases',
                'constraints': [models.UniqueConstraint(fields=('value_normalized',), name='journal_alias_norm_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='specialtyjournal',
            constraint=models.UniqueConstraint(fields=('specialty', 'journal'), name='specialty_journal_unique'),
        ),
    ]
