#!/usr/bin/env python3
"""Regenerate the MedPally brand assets in `static/img/brand/`.

Everything downstream of the monogram is derived, so the icons, favicons and
the Open Graph card can be rebuilt from one place whenever the brand colour or
the letterform changes:

    python tools/brand_assets.py

The monogram is a flat-topped grotesk M: two vertical stems joined by a
symmetric V whose mitred vertex stops short of the baseline.  It is built by
offsetting the skeleton polyline by half the stroke weight and mitring the
joins, then cutting the two top mitres flat at the cap line — the flat apexes
are what stop it reading as a stroked polyline.

Rasterisation uses headless Chrome, which is the only SVG renderer we can rely
on being present on a developer machine.  The PNGs are committed, so this
script is only needed when the artwork itself changes.
"""

from __future__ import annotations

import math
import re
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "static" / "img" / "brand"

NAVY = "#123A4D"
CANVAS = 512
TILE_RADIUS = 112  # 22% of the canvas, the iOS/Android app-icon convention

# Letterform, in canvas units.
LETTER_WIDTH = 246.0
LETTER_HEIGHT = 192.0
STROKE_WEIGHT = 48.0
VERTEX_FRACTION = 0.74  # how far down the cap height the two diagonals meet

CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"


# ---------------------------------------------------------------- letterform


def monogram_path(
    width: float = LETTER_WIDTH,
    height: float = LETTER_HEIGHT,
    weight: float = STROKE_WEIGHT,
    vertex_fraction: float = VERTEX_FRACTION,
    centre: float = CANVAS / 2,
) -> str:
    """The M as a single closed outline, optically centred on `centre`."""
    half = weight / 2
    top = centre - height / 2
    bottom = centre + height / 2
    # Stem centrelines: the outline sits half a stroke outside each.
    left = centre - width / 2 + half
    right = centre + width / 2 - half
    vertex_y = top + (bottom - top) * vertex_fraction

    run, rise = centre - left, vertex_y - top
    length = math.hypot(run, rise)
    # Horizontal shift of an edge offset half a stroke from the diagonal, and
    # the depth of the mitre where the two diagonals meet.
    edge_dx = half * length / rise
    mitre = half * length / run

    apex_left = left + edge_dx
    apex_right = right - edge_dx
    counter_y = top + (half + edge_dx) * rise / run

    def n(value: float) -> str:
        return f"{value:.2f}".rstrip("0").rstrip(".")

    return (
        f"M{n(left - half)} {n(bottom)}"
        f"V{n(top)}"
        f"H{n(apex_left)}"
        f"L{n(centre)} {n(vertex_y - mitre)}"
        f"L{n(apex_right)} {n(top)}"
        f"H{n(right + half)}"
        f"V{n(bottom)}"
        f"H{n(right - half)}"
        f"V{n(counter_y)}"
        f"L{n(centre)} {n(vertex_y + mitre)}"
        f"L{n(left + half)} {n(counter_y)}"
        f"V{n(bottom)}"
        "Z"
    )


def _shift(path: str, dx: float, dy: float) -> str:
    """Translate an outline made only of M/L/H/V commands."""

    def move(match: re.Match[str]) -> str:
        command, body = match.group(1), match.group(2)
        values = [float(value) for value in re.findall(r"-?\d+(?:\.\d+)?", body)]
        if command == "H":
            values = [value - dx for value in values]
        elif command == "V":
            values = [value - dy for value in values]
        else:
            values = [v - (dx if i % 2 == 0 else dy) for i, v in enumerate(values)]
        return command + " ".join(f"{v:.2f}".rstrip("0").rstrip(".") for v in values)

    return re.sub(r"([MLHV])([-\d. ]+)", move, path)


# ---------------------------------------------------------------- svg sources

HEADER = (
    "<!-- MedPally monogram — generated by tools/brand_assets.py. "
    "Edit that script, not this file. -->\n"
)


def svg_sources() -> dict[str, str]:
    path = monogram_path()
    glyph = _shift(path, (CANVAS - LETTER_WIDTH) / 2, (CANVAS - LETTER_HEIGHT) / 2)
    # Android crops adaptive icons to a circle 80% of the canvas, so the tile
    # bleeds to the edge and the letter is enlarged into the safe area.
    maskable_scale = 1.22
    maskable_offset = (CANVAS - CANVAS * maskable_scale) / 2

    return {
        "logo-mark.svg": f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512" role="img" aria-label="MedPally">
  <rect width="512" height="512" rx="{TILE_RADIUS}" fill="{NAVY}"/>
  <path d="{path}" fill="#fff"/>
</svg>
""",
        "logo-mark-maskable.svg": f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512" role="img" aria-label="MedPally">
  <rect width="512" height="512" fill="{NAVY}"/>
  <path d="{path}" fill="#fff" transform="translate({maskable_offset:.2f} {maskable_offset:.2f}) scale({maskable_scale})"/>
</svg>
""",
        # iOS rounds the corners itself, so the touch icon stays a full square.
        "logo-mark-square.svg": f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512" role="img" aria-label="MedPally">
  <rect width="512" height="512" fill="{NAVY}"/>
  <path d="{path}" fill="#fff"/>
</svg>
""",
        # The bare letterform, for a background the page already owns.
        "logo-glyph.svg": f"""{HEADER}<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {LETTER_WIDTH:.0f} {LETTER_HEIGHT:.0f}" width="{LETTER_WIDTH:.0f}" height="{LETTER_HEIGHT:.0f}" role="img" aria-label="MedPally">
  <path d="{glyph}" fill="currentColor"/>
</svg>
""",
    }


OG_CARD = """<!doctype html>
<meta charset="utf-8">
<style>
  * {{ margin: 0; box-sizing: border-box; }}
  body {{
    width: 1200px; height: 630px; background: {navy};
    background-image: linear-gradient(160deg, #17475D 0%, {navy} 46%, #0C2634 100%);
    display: flex; flex-direction: column; justify-content: center; gap: 30px;
    padding: 0 92px; color: #fff;
    font-family: -apple-system, "SF Pro Display", "Helvetica Neue", sans-serif;
  }}
  .lockup {{ display: flex; align-items: center; gap: 26px; }}
  .lockup svg {{ width: 104px; height: 104px; }}
  .name {{ font-size: 62px; font-weight: 800; letter-spacing: -0.035em; }}
  h1 {{ font-size: 46px; font-weight: 600; letter-spacing: -0.022em; line-height: 1.24; max-width: 900px; }}
  p {{ font-size: 26px; color: rgba(255,255,255,0.62); letter-spacing: -0.005em; }}
  .rule {{ width: 78px; height: 5px; border-radius: 3px; background: rgba(255,255,255,0.28); }}
</style>
<div class="lockup">
  <svg viewBox="0 0 512 512"><rect width="512" height="512" rx="{radius}" fill="#fff"/><path d="{path}" fill="{navy}"/></svg>
  <span class="name">MedPally</span>
</div>
<div class="rule"></div>
<h1>The week&rsquo;s research from the journals you actually read.</h1>
<p>Every paper summarised into a few lines you can scan on the ward.</p>
"""


# ---------------------------------------------------------------- rasterising


def chrome_screenshot(source: Path, target: Path, width: int, height: int) -> None:
    subprocess.run(
        [
            CHROME,
            "--headless",
            "--disable-gpu",
            "--hide-scrollbars",
            "--force-device-scale-factor=1",
            "--default-background-color=00000000",
            f"--window-size={width},{height}",
            "--virtual-time-budget=3000",
            f"--screenshot={target}",
            str(source),
        ],
        check=True,
        capture_output=True,
    )


def render_svg(name: str, target: Path) -> Path:
    """Rasterise one of the brand SVGs at its own 512px size.

    Only at its own size: asked to draw an SVG smaller than its intrinsic
    width, headless Chrome applies the viewBox scale twice and the artwork
    lands in a corner of the frame.  Every smaller icon is a downscale of this
    render instead.
    """
    chrome_screenshot(OUT / name, target, CANVAS, CANVAS)
    print(f"  {target.name}  {CANVAS}x{CANVAS}")
    return target


def resize(source: Path, target: Path, size: int) -> Path:
    """Downscale a rendered icon. sips ships with macOS and keeps the alpha."""
    subprocess.run(
        ["sips", "-z", str(size), str(size), str(source), "--out", str(target)],
        check=True,
        capture_output=True,
    )
    print(f"  {target.name}  {size}x{size}")
    return target


def build_ico(target: Path, sources: list[tuple[int, Path]]) -> None:
    """Pack PNGs into an .ico — every browser since IE11 reads PNG-in-ICO."""
    entries, blobs, offset = [], [], 6 + 16 * len(sources)
    for size, png in sources:
        data = png.read_bytes()
        entries.append(
            struct.pack(
                "<BBBBHHII",
                size if size < 256 else 0,
                size if size < 256 else 0,
                0,
                0,
                1,
                32,
                len(data),
                offset,
            )
        )
        blobs.append(data)
        offset += len(data)
    target.write_bytes(
        struct.pack("<HHH", 0, 1, len(sources)) + b"".join(entries) + b"".join(blobs)
    )
    print(f"  {target.name}  {', '.join(str(size) for size, _ in sources)}")


def main() -> int:
    if not Path(CHROME).exists():
        print(f"Chrome not found at {CHROME} — needed to rasterise the icons.", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    print(f"writing {OUT.relative_to(ROOT)}")
    for name, body in svg_sources().items():
        (OUT / name).write_text(body, encoding="utf-8")
        print(f"  {name}")

    work = Path(tempfile.mkdtemp(prefix="medpally-brand-"))
    try:
        mark = render_svg("logo-mark.svg", OUT / "icon-512.png")
        maskable = render_svg("logo-mark-maskable.svg", OUT / "icon-maskable-512.png")
        square = render_svg("logo-mark-square.svg", work / "square-512.png")

        resize(mark, OUT / "icon-192.png", 192)
        resize(maskable, OUT / "icon-maskable-192.png", 192)
        resize(square, OUT / "apple-touch-icon.png", 180)

        favicons = [
            (size, resize(mark, work / f"favicon-{size}.png", size)) for size in (16, 32, 48)
        ]
        shutil.copyfile(work / "favicon-32.png", OUT / "favicon-32.png")
        build_ico(OUT / "favicon.ico", favicons)

        card = work / "og.html"
        card.write_text(
            OG_CARD.format(navy=NAVY, path=monogram_path(), radius=TILE_RADIUS),
            encoding="utf-8",
        )
        chrome_screenshot(card, OUT / "og-image.png", 1200, 630)
        print("  og-image.png  1200x630")
    finally:
        shutil.rmtree(work, ignore_errors=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
