# Generated by Django 5.2.16 on 2026-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_userpaperstate_searched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaperstate',
            name='external_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
